asdf_add_go:
	asdf plugin add golang

asdf_list_versions:
	asdf list all golang

asdf_install_golang_1_14:
	asdf install golang 1.14

#create_go_path:
#  export PATH=$$PATH:$(go env GOPATH)/bin
#  export GOPATH=$(go env GOPATH)

