asdf_add_php:
	asdf plugin add php

asdf_list_versions:
	asdf list all php

asdf_install_php_5_6_40:
	#PHP_WITHOUT_PEAR=yes asdf install php 5.6.40
	sudo add-apt-repository -y ppa:ondrej/php
	sudo apt update
	sudo apt install php5.6
